version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    version: 14.4.0
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node -v
            - run: npm install
            - run: npm test
workflows:
  jobs:
    - build-and-test