version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test
workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.4.0"]